### ISSUE TITLE
Why is the module private on npm

### ISSUE THREAD

**Issue by rogerfranklin2** [sky-uk/nowtv-react-toolkit#39]
Just curious why the module is private on npm but the repo is public so people can get it anyway?

I think we should make the module public, any objections?

**Comment by bdo** [comment]
Agreed, public would make more sense to me as well. :+1:

**Comment by peter-mouland** [comment]
do e have anything on here relating to un-released products?

**Comment by rogerfranklin2** [comment]
I don't think we do.

If we do, we shouldn't as the repo is public.

**Comment by peter-mouland** [comment]
ah - sorry, misunderstood.  It's on the private repo because we put it there.  The nav was on the private repo so to be consistent we decided to put this there too.  We figured that actually, no one will use this externally (its no google's material design or twitter bootstrap) as we don't have the dedicated teams to support it.

i think if we keep the different 'global' project in different scopes it will get confusing. everything in one place is simpler to setup / remember.
